"""Back to back

Revision ID: 0020f0a6297b
Revises: 420c11bb18aa
Create Date: 2025-05-30 18:29:31.690760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0020f0a6297b'
down_revision: Union[str, None] = '420c11bb18aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.add_column('tournaments', sa.Column('coach_id', sa.Integer(), nullable=True))
    op.drop_constraint('tournaments_ibfk_1', 'tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'tournaments', 'users', ['coach_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tournaments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.create_foreign_key('tournaments_ibfk_1', 'tournaments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tournaments', 'coach_id')
    op.create_table('events',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('coach_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_start', mysql.DATETIME(), nullable=False),
    sa.Column('date_end', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], name='events_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['event_types.id'], name='events_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
