"""Add events table

Revision ID: 02c63681334f
Revises: 1dc218d4a9a4
Create Date: 2025-05-30 18:33:13.472681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '02c63681334f'
down_revision: Union[str, None] = '1dc218d4a9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['event_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('tournaments_ibfk_2', 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tournaments_ibfk_2', 'tournaments', 'event_types', ['type_id'], ['id'], ondelete='SET NULL')
    op.drop_table('events')
    # ### end Alembic commands ###
