"""Add events table relationships

Revision ID: 1051a410a132
Revises: 9f96bf4fa5ef
Create Date: 2025-05-30 21:10:33.552564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1051a410a132'
down_revision: Union[str, None] = '9f96bf4fa5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'results', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'event_id')
    # ### end Alembic commands ###
