"""Add role table

Revision ID: 406cd31f6473
Revises: 94126a6bb49c
Create Date: 2025-05-27 13:52:19.027395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '406cd31f6473'
down_revision: Union[str, None] = '94126a6bb49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.alter_column('users', 'date_joined',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('users', 'date_joined',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'phone_number')
    op.drop_table('roles')
    # ### end Alembic commands ###
