"""Delete relationship with sportsmen and users

Revision ID: 65071fdc6419
Revises: 87ccf20b8c44
Create Date: 2025-05-29 22:00:10.920430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65071fdc6419'
down_revision: Union[str, None] = '87ccf20b8c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sportsmen_ibfk_1', 'sportsmen', type_='foreignkey')
    op.drop_column('sportsmen', 'coach_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sportsmen', sa.Column('coach_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sportsmen_ibfk_1', 'sportsmen', 'users', ['coach_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
