"""Back to back 2

Revision ID: 70cab006959b
Revises: 0020f0a6297b
Create Date: 2025-05-30 18:30:20.287905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '70cab006959b'
down_revision: Union[str, None] = '0020f0a6297b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('tournaments_ibfk_3', 'tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'tournaments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tournaments', 'coach_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('coach_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.create_foreign_key('tournaments_ibfk_3', 'tournaments', 'users', ['coach_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tournaments', 'user_id')
    # ### end Alembic commands ###
