"""Delete relationship with sportsmen and results

Revision ID: 87ccf20b8c44
Revises: 15ce80aa701f
Create Date: 2025-05-29 21:59:04.150475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87ccf20b8c44'
down_revision: Union[str, None] = '15ce80aa701f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('results_ibfk_2', 'results', type_='foreignkey')
    op.drop_column('results', 'sportsman_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('sportsman_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('results_ibfk_2', 'results', 'sportsmen', ['sportsman_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
