"""Delete tournaments id in relults

Revision ID: 919d937dc962
Revises: f0a50a630627
Create Date: 2025-05-30 21:28:58.628502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '919d937dc962'
down_revision: Union[str, None] = 'f0a50a630627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('results_ibfk_3', 'results', type_='foreignkey')
    op.drop_column('results', 'tournament_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('tournament_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('results_ibfk_3', 'results', 'tournaments', ['tournament_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
