"""Add user_id in TournamentORM

Revision ID: 94126a6bb49c
Revises: dc375d630d59
Create Date: 2025-05-05 21:17:34.889762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94126a6bb49c'
down_revision: Union[str, None] = 'dc375d630d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'user_id')
    # ### end Alembic commands ###
