"""Add type_id in tournaments tablr

Revision ID: c3229aa5680a
Revises: 7ca46c48dedb
Create Date: 2025-05-30 18:21:24.712763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3229aa5680a'
down_revision: Union[str, None] = '7ca46c48dedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'event_types', ['type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'type_id')
    # ### end Alembic commands ###
