"""First migration

Revision ID: dc375d630d59
Revises: 
Create Date: 2025-05-04 23:40:02.901846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc375d630d59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('img_url', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sportsmen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('img_url', sa.String(length=1000), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sportsman_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('points_scored', sa.Integer(), nullable=False),
    sa.Column('points_missed', sa.Integer(), nullable=False),
    sa.Column('number_of_fights', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sportsman_id'], ['sportsmen.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('sportsmen')
    op.drop_table('users')
    op.drop_table('tournaments')
    op.drop_table('places')
    # ### end Alembic commands ###
