"""Edit foreign key in student_events

Revision ID: e876c1dfb4da
Revises: 313c530b7f19
Create Date: 2025-05-31 15:08:38.755197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e876c1dfb4da'
down_revision: Union[str, None] = '313c530b7f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_events_ibfk_2', 'students_events', type_='foreignkey')
    op.create_foreign_key(None, 'students_events', 'student_profiles', ['student_id'], ['student_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students_events', type_='foreignkey')
    op.create_foreign_key('students_events_ibfk_2', 'students_events', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
