"""Delete tournaments table user_id and type_id

Revision ID: f0a50a630627
Revises: 4a8f1709b1eb
Create Date: 2025-05-30 21:15:59.553621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0a50a630627'
down_revision: Union[str, None] = '4a8f1709b1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tournaments_ibfk_4', 'tournaments', type_='foreignkey')
    op.drop_constraint('tournaments_ibfk_3', 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'type_id')
    op.drop_column('tournaments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tournaments_ibfk_3', 'tournaments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tournaments_ibfk_4', 'tournaments', 'event_types', ['type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
