"""Delete sportsmen tables

Revision ID: fc32b39abd35
Revises: 65071fdc6419
Create Date: 2025-05-29 22:01:39.559088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc32b39abd35'
down_revision: Union[str, None] = '65071fdc6419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sportsmen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sportsmen',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('patronymic', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('date_of_birth', mysql.DATETIME(), nullable=False),
    sa.Column('img_url', mysql.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
